### PR TITLE
Updated schema

### PR DESCRIPTION
**Pull request by CampbellSDC**
Just want to see if this is what we are looking for in regards to schema before I get too far down the road

### CODE REVIEW

**Review by raygdev — CHANGES_REQUESTED** [review]
So I like the schema setup... It looks good, probably better than I had imagined. I would like some other things on it though. for size, type, and font:
```javascript
size: { type: String, required: true },
type: { type: String, required: true },
font: { type: String, required: true },
```
for the letters, we don't need to have `sym` as an array. We are going to require this as well, and it should be a string, at least in my head. Was this something to have a more fine-grained control over? We need to know how much of each letter is available? Correct? Or did I misunderstand?

So something like:
```javascript
letters: {
   type:[{
      sym: { type: String, required: true },
      totalStock: Number,
      numAvailable: Number
   }],
   required: true
```
If you have some suggestions or reasons why you would like it this way, I'm all ears. Otherwise, everything you have is really great! Let me know!

**Comment by CampbellSDC** [comment]
Ok, made those updates - and there was nothing specific that I was going for in regards to how those were set up. For the array, I thought it was needed to be able to select from a specific "set" of letters that we build, but I guess we do custom orders, so just allowing strings will be good. 

Also, in the README, you have the CRUD operations ('Methods')...are these the actual CRUD operations that will be done in the server.js file, or are these mongoose methods that need to be used...or do we use those methods within the CRUD operations? Sorry, still trying to piece a lot of this together

**Comment by raygdev** [comment]
> Also, in the README, you have the CRUD operations ('Methods')...are these the actual CRUD operations that will be done in the server.js file, or are these mongoose methods that need to be used...or do we use those methods within the CRUD operations? Sorry, still trying to piece a lot of this together

So we are going to put those in a different directory. I'll spin that up after we get this commit resolved. I will just set up the boiler plate for what I think we'll need, and go over it with you. Also, I think I'll just start creating issues for features or fixes or adding something and will will work on those in different branches. 

Also, later this evening, I'm going to give you write access to the repo so that you can also do reviews on my code. Please commit your changes to your branch so I can review and we can continue! It should update the pull request automatically.

**Review by raygdev — APPROVED** [review]
This looks good to me! Thank you! I'll get started on the other stuff and discuss with you later!

**Pull request merged**
