### PR TITLE
created client directory & vite

### PR DESCRIPTION
**Pull request by CampbellSDC**

### CODE REVIEW

**Review by raygdev — COMMENTED** [review]
Looks good, the only thing I would suggest at this point is to have the client folder as the top level directory for the frontend. Remove everything from the simply-lit directory and put it into the client directory. Then delete the simply-lit directory.

**Comment by CampbellSDC** [comment]
I would need to overwrite the package.json file that was initially created in the 'client' folder with the one that is in the 'simply-lit' folder. Is that what you want to do? Once you cd into the client directory and install vite, it automatically sets up a new directory within the client directory, so that's where simply-lit came from.

**Comment by raygdev** [comment]
Did you do something like `npm create vite@latest simply-lit`? If so, that is why the directory was added. You should just be able to run `npm create vite@latest` and it shouldn't prompt for a directory. It should just install in the directory you are currently in. I could be wrong though. You don't need to overwrite everything. Just drag and drop the files into that directory. If vs code won't allow you, you can search for the files and folders on your pc and drag and drop them that way. Whatever you feel is easiest.

**Comment by raygdev** [comment]
Ah, i get it.... it was prompting you for the name when you ran install

**Comment by raygdev** [comment]
Ok, so what you would need to do is this. Delete the client folder. Create a new client folder. run `npm create vite@latest` again. When it prompts for a project directory type `.` this will tell vite you want it installed in the current directory.

**Comment by CampbellSDC** [comment]
Ahhh, ok. I've done the same thing with a couple projects and hated that it created that sub-directory, because then you have to cd into that to do your npm run dev. 

Ok. I'll fix that when I get home from work.

**Pull request merged**
