### PR TITLE
updated some color on header

### PR DESCRIPTION
**Pull request by CampbellSDC**

### CODE REVIEW

**Comment by raygdev** [comment]
@CampbellSDC I think it is erroring because we are mixing apis here. Browser router doesn't have some of the components available that the data router does. Form won't work inside the browser router, and neither will useSubmit. Everything g else currently actually looks good. If you want to experiment, you would likely need to import `createRoutesFromElements` in the app component and change the browser router in main.jsx to `Router` to get that working.

**Comment by CampbellSDC** [comment]
Ah, ok. I'll need to have it in front of me, but off the top of my head, i will instead need to use the RouteProvider and then the createRouteFromElement? I'm sure there are a couple other things that will also need to be changed. Is this the direction you want to go, or would something else be an easier solution?

**Comment by raygdev** [comment]
@CampbellSDC Sorry for all the delay... I've been struggling lol! I just pushed to your fork on the playground branch. Pull in those changes and then do whatever else you need to. All I did was update the colors on the links since the header colors were blending with the text. I like what you've done for sure though! It looks good. I like the login form as well! Nice job! I'll try and get those routes for login setup here soon. I'm sorry for holding us up man!

**Comment by CampbellSDC** [comment]
Sorry, I was trying to find this commit to respond to your message. Don't worry about the project. It's not the end of the world if there is ever a delay. I haven't touched it in like a week lol. I went to that Refactr conference, and instantly felt the imposter syndrome and have been doing leetcode stuff instead. So no need to ever apologize, bro! Really appreciate all you have done to get us to this point

**Pull request merged**
